#!/bin/bash

cd ../../
if [ -d content ]
  then echo "Content folder already exists."
  else 
    mkdir content && echo "create content directory"
    cp mra/admin/init/*.md content/ && echo "copy init content files"
    cp mra/admin/init/*.conf mra/ && echo "copy init setting files"
    cp mra/admin/init/.creds mra/ && echo "copy credential file"
    mkdir mra/tmp && echo "create cache directory"
    
fi
