#!/bin/bash

cd ../../
if [ -d content ]
  then echo "Content folder already exists."
  else 
    mkdir content && echo "content directory created"
    cp mra/admin/init/*.md content/ && echo "copied init content files"
    cp mra/admin/init/*.conf mra/ && echo "copied init setting files"
    mkdir mra/tmp && echo "created cache directory"
fi
